language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - yarn global add codecov
  - yarn bootstrap
script:
  - yarn type-check
  - yarn test --coverage --bail --runInBand --silent
  - codecov --token=$CODECOV_TOKEN
  - if [ $TRAVIS_BRANCH == 'master' ]; then yarn storybook:deploy --ci --host-token-env-variable=$GITHUB_TOKEN; fi
