language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - yarn global add codecov
  - yarn bootstrap
script:
  - yarn type-check
  - yarn test --coverage --bail --runInBand --silent
  - codecov --token=$CODECOV_TOKEN
